from flask import Blueprint, render_template, Flask, current_app, jsonify
from flask_login import login_required, current_user
from . import db
from . import app
from .models import Flight, Seat, Passenger
import random


passengers = Blueprint('passengers', __name__)


def create_new_passenger():
    first_name = random.choices([
        'Aaron',
        'Adam',
        'Eric',
        'William',
        'Henry',
        'George',
        'Andrew',
        'Peter',
        'Liam',
        'Noah',
        'James',
        'Logan',
        'Bejamin',
        'Mason',
        'Elijah',
        'Oliver',
        'Jacob',
        'Joseph',
    ])[0]

    second_name = random.choices([
        'Smith',
        'Johnson',
        'Williams',
        'Brown',
        'Jones',
        'Garcia',
        'Miller',
        'Davis',
        'Rodriguez',
        'Martinez',
        'Hernandez',
        'Lopez',
        'Gonzalez',
        'Wilson',
        'Anderson',
        'Thomas',
        'Taylor',
        'Moore',
        'Jackson',
        'Martin',
        'Lee',
        'Perez',
        'Thompson',
        'White',
        'Harris',
        'Sanchez',
        'Clark',
        'Ramirez',
        'Lewis',
        'Robinson',
        'Walker',
        'Young',
        'Allen',
        'King',
        'Wright',
        'Scott',
        'Torres',
        'Nguyen',
        'Hill',
        'Flores',
        'Green',
        'Adams',
        'Nelson',
        'Baker',
        'Hall',
        'Rivera',
        'Campbell',
        'Mitchell',
        'Carter',
        'Roberts',
        'Gomez',
        'Phillips',
        'Evans',
        'Turner',
        'Diaz',
        'Parker',
        'Cruz',
        'Edwards',
        'Collins',
        'Reyes',
        'Stewart',
        'Morris',
        'Morales',
        'Murphy',
        'Cook',
        'Rogers',
        'Gutierrez',
        'Ortiz',
        'Morgan',
        'Cooper',
        'Peterson',
        'Bailey',
        'Reed',
        'Kelly',
        'Howard',
        'Ramos',
        'Kim',
        'Cox',
        'Ward',
        'Richardson',
        'Watson',
        'Brooks',
        'Chavez',
        'Wood',
        'James',
        'Bennett',
        'Gray',
        'Mendoza',
        'Ruiz',
        'Hughes',
        'Price',
        'Alvarez',
        'Castillo',
        'Sanders',
        'Patel',
        'Myers',
        'Long',
        'Ross',
        'Foster',
        'Jimenez',
        'Powell',
        'Jenkins',
        'Perry',
        'Russell',
        'Sullivan',
        'Bell',
        'Coleman',
        'Butler',
        'Henderson',
        'Barnes',
        'Gonzales',
        'Fisher',
        'Vasquez',
        'Simmons',
        'Romero',
        'Jordan',
        'Patterson',
        'Alexander',
        'Hamilton',
        'Graham',
        'Reynolds',
        'Griffin',
        'Wallace',
        'Moreno',
        'West',
        'Cole',
        'Hayes',
        'Bryant',
        'Herrera',
        'Gibson',
        'Ellis',
        'Tran',
        'Medina',
        'Aguilar',
        'Stevens',
        'Murray',
        'Ford',
        'Castro',
        'Marshall',
        'Owens',
        'Harrison',
        'Fernandez',
        'Mcdonald',
        'Woods',
        'Washington',
        'Kennedy',
        'Wells',
        'Vargas',
        'Henry',
        'Chen',
        'Freeman',
        'Webb',
        'Tucker',
        'Guzman',
        'Burns',
        'Crawford',
        'Olson',
        'Simpson',
        'Porter',
        'Hunter',
        'Gordon',
        'Mendez',
        'Silva',
        'Shaw',
        'Snyder',
        'Mason',
        'Dixon',
        'Munoz',
        'Hunt',
        'Hicks',
        'Holmes',
        'Palmer',
        'Wagner',
        'Black',
        'Robertson',
        'Boyd',
        'Rose',
        'Stone',
        'Salazar',
        'Fox',
        'Warren',
        'Mills',
        'Meyer',
        'Rice',
        'Schmidt',
        'Garza',
        'Daniels',
        'Ferguson',
        'Nichols',
        'Stephens',
        'Soto',
        'Weaver',
        'Ryan',
        'Gardner',
        'Payne',
        'Grant',
        'Dunn',
        'Kelley',
        'Spencer',
        'Hawkins',
        'Arnold',
        'Pierce',
        'Vazquez',
        'Hansen',
        'Peters',
        'Santos',
        'Hart',
        'Bradley',
        'Knight',
        'Elliott',
        'Cunningham',
        'Duncan',
        'Armstrong',
        'Hudson',
        'Carroll',
        'Lane',
        'Riley',
        'Andrews',
        'Alvarado',
        'Ray',
        'Delgado',
        'Berry',
        'Perkins',
        'Hoffman',
        'Johnston',
        'Matthews',
        'Pena',
        'Richards',
        'Contreras',
        'Willis',
        'Carpenter',
        'Lawrence',
        'Sandoval',
        'Guerrero',
        'George',
        'Chapman',
        'Rios',
        'Estrada',
        'Ortega',
        'Watkins',
        'Greene',
        'Nunez',
        'Wheeler',
        'Valdez',
        'Harper',
        'Burke',
        'Larson',
        'Santiago',
        'Maldonado',
        'Morrison',
        'Franklin',
        'Carlson',
        'Austin',
        'Dominguez',
        'Carr',
        'Lawson',
        'Jacobs',
        'Obrien',
        'Lynch',
        'Singh',
        'Vega',
        'Bishop',
        'Montgomery',
        'Oliver',
        'Jensen',
        'Harvey',
        'Williamson',
        'Gilbert',
        'Dean',
        'Sims',
        'Espinoza',
        'Howell',
        'Li',
        'Wong',
        'Reid',
        'Hanson',
        'Le',
        'Mccoy',
        'Garrett',
        'Burton',
        'Fuller',
        'Wang',
        'Weber',
        'Welch',
        'Rojas',
        'Lucas',
        'Marquez',
        'Fields',
        'Park',
        'Yang',
        'Little',
        'Banks',
        'Padilla',
        'Day',
        'Walsh',
        'Bowman',
        'Schultz',
        'Luna',
        'Fowler',
        'Mejia',
        'Davidson',
        'Acosta',
        'Brewer',
        'May',
        'Holland',
        'Juarez',
        'Newman',
        'Pearson',
        'Curtis',
        'Cortez',
        'Douglas',
        'Schneider',
        'Joseph',
        'Barrett',
        'Navarro',
        'Figueroa',
        'Keller',
        'Avila',
        'Wade',
        'Molina',
        'Stanley',
        'Hopkins',
        'Campos',
        'Barnett',
        'Bates',
        'Chambers',
        'Caldwell',
        'Beck',
        'Lambert',
        'Miranda',
        'Byrd',
        'Craig',
        'Ayala',
        'Lowe',
        'Frazier',
        'Powers',
        'Neal',
        'Leonard',
        'Gregory',
        'Carrillo',
        'Sutton',
        'Fleming',
        'Rhodes',
        'Shelton',
        'Schwartz',
        'Norris',
        'Jennings',
        'Watts',
        'Duran',
        'Walters',
        'Cohen',
        'Mcdaniel',
        'Moran',
        'Parks',
        'Steele',
        'Vaughn',
        'Becker',
        'Holt',
        'Deleon',
        'Barker',
        'Terry',
        'Hale',
        'Leon',
        'Hail',
        'Benson',
        'Haynes',
        'Horton',
        'Miles',
        'Lyons',
        'Pham',
        'Graves',
        'Bush',
        'Thornton',
        'Wolfe',
        'Warner',
        'Cabrera',
        'Mckinney',
        'Mann',
        'Zimmerman',
        'Dawson',
        'Lara',
        'Fletcher',
        'Page',
        'Mccarthy',
        'Love',
        'Robles',
        'Cervantes',
        'Solis',
        'Erickson',
        'Reeves',
        'Chang',
        'Klein',
        'Salinas',
        'Fuentes',
        'Baldwin',
        'Daniel',
        'Simon',
        'Velasquez',
        'Hardy',
        'Higgins',
        'Aguirre',
        'Lin',
        'Cummings',
        'Chandler',
        'Sharp',
        'Barber',
        'Bowen',
        'Ochoa',
        'Dennis',
        'Robbins',
        'Liu',
        'Ramsey',
        'Francis',
        'Griffith',
        'Paul',
        'Blair',
        'Oconnor',
        'Cardenas',
        'Pacheco',
        'Cross',
        'Calderon',
        'Quinn',
        'Moss',
        'Swanson',
        'Chan',
        'Rivas',
        'Khan',
        'Rodgers',
        'Serrano',
        'Fitzgerald',
        'Rosales',
        'Stevenson',
        'Christensen',
        'Manning',
        'Gill',
        'Curry',
        'Mclaughlin',
        'Harmon',
        'Mcgee',
        'Gross',
        'Doyle',
        'Garner',
        'Newton',
        'Burgess',
        'Reese',
        'Walton',
        'Blake',
        'Trujillo',
        'Adkins',
        'Brady',
        'Goodman',
        'Roman',
        'Webster',
        'Goodwin',
        'Fischer',
        'Huang',
        'Potter',
        'Delacruz',
        'Montoya',
        'Todd',
        'Wu',
        'Hines',
        'Mullins',
        'Castaneda',
        'Malone',
        'Cannon',
        'Tate',
        'Mack',
        'Sherman',
        'Hubbard',
        'Hodges',
        'Zhang',
        'Guerra',
        'Wolf',
        'Valencia',
        'Saunders',
        'Franco',
        'Rowe',
        'Gallagher',
        'Farmer',
        'Hammond',
        'Hampton',
        'Townsend',
        'Ingram',
        'Wise',
        'Gallegos',
        'Clarke',
        'Barton',
        'Schroeder',
        'Maxwell',
        'Waters',
        'Logan',
        'Camacho',
        'Strickland',
        'Norman',
        'Person',
        'Colon',
        'Parsons',
        'Frank',
        'Harrington',
        'Glover',
        'Osborne',
        'Buchanan',
        'Casey',
        'Floyd',
        'Patton',
        'Ibarra',
        'Ball',
        'Tyler',
        'Suarez',
        'Bowers',
        'Orozco',
        'Salas',
        'Cobb',
        'Gibbs',
        'Andrade',
        'Bauer',
        'Conner',
        'Moody',
        'Escobar',
        'Mcguire',
        'Lloyd',
        'Mueller',
        'Hartman',
        'French',
        'Kramer',
        'Mcbride',
        'Pope',
        'Lindsey',
        'Velazquez',
        'Norton',
        'Mccormick',
        'Sparks',
        'Flynn',
        'Yates',
        'Hogan',
        'Marsh',
        'Macias',
        'Villanueva',
        'Zamora',
        'Pratt',
        'Stokes',
        'Owen',
        'Ballard',
        'Lang',
        'Brock',
        'Villarreal',
        'Charles',
        'Drake',
        'Barrera',
        'Cain',
        'Patrick',
        'Pineda',
        'Burnett',
        'Mercado',
        'Santana',
        'Shepherd',
        'Bautista',
        'Ali',
        'Shaffer',
        'Lamb',
        'Trevino',
        'Mckenzie',
        'Hess',
        'Beil',
        'Olsen',
        'Cochran',
        'Morton',
        'Nash',
        'Wilkins',
        'Petersen',
        'Briggs',
        'Shah',
        'Roth',
        'Nicholson',
        'Holloway',
        'Lozano',
        'Rangel',
        'Flowers',
        'Hoover',
        'Short',
        'Arias',
        'Mora',
        'Valenzuela',
        'Bryan',
        'Meyers',
        'Weiss',
        'Underwood',
        'Bass',
        'Greer',
        'Summers',
        'Houston',
        'Carson',
        'Morrow',
        'Clayton',
        'Whitaker',
        'Decker',
        'Yoder',
        'Collier',
        'Zuniga',
        'Carey',
        'Wilcox',
        'Melendez',
        'Poole',
        'Roberson',
        'Larsen',
        'Conley',
        'Davenport',
        'Copeland',
        'Massey',
        'Lam',
        'Huff',
        'Rocha',
        'Cameron',
        'Jefferson',
        'Hood',
        'Monroe',
        'Anthony',
        'Pittman',
        'Huynh',
        'Randall',
        'Singleton',
        'Kirk',
        'Combs',
        'Mathis',
        'Christian',
        'Skinner',
        'Bradford',
        'Richard',
        'Galvan',
        'Wall',
        'Boone',
        'Kirby',
        'Wilkinson',
        'Bridges',
        'Bruce',
        'Atkinson',
        'Velez',
        'Meza',
        'Roy',
        'Vincent',
        'York',
        'Hodge',
        'Villa',
        'Abbott',
        'Allison',
        'Tapia',
        'Gates',
        'Chase',
        'Sosa',
        'Sweeney',
        'Farrell',
        'Wyatt',
        'Dalton',
        'Horn',
        'Barron',
        'Phelps',
        'Yu',
        'Dickerson',
        'Heath',
        'Foley',
        'Atkins',
        'Mathews',
        'Bonilla',
        'Acevedo',
        'Benitez',
        'Zavala',
        'Hensley',
        'Glenn',
        'Cisneros',
        'Harrell',
        'Shields',
        'Rubio',
        'Huffman',
        'Choi',
        'Boyer',
        'Garrison',
        'Arroyo',
        'Bond',
        'Kane',
        'Hancock',
        'Callahan',
        'Dillon',
        'Cline',
        'Wiggins',
        'Grimes',
        'Arellano',
        'Melton',
        'Oneill',
        'Savage',
        'Ho',
        'Beltran',
        'Pitts',
        'Parrish',
        'Ponce',
        'Rich',
        'Booth',
        'Koch',
        'Golden',
        'Ware',
        'Brennan',
        'Mcdowell',
        'Marks',
        'Cantu',
        'Humphrey',
        'Baxter',
        'Sawyer',
        'Clay',
        'Tanner',
        'Hutchinson',
        'Kaur',
        'Berg',
        'Wiley',
        'Gilmore',
        'Russo',
        'Villegas',
        'Hobbs',
        'Keith',
        'Wilkerson',
        'Ahmed',
        'Beard',
        'Mcclain',
        'Montes',
        'Mata',
        'Rosario',
        'Vang',
        'Walter',
        'Henson',
        'Oneal',
        'Mosley',
        'Mcclure',
        'Beasley',
        'Stephenson',
        'Snow',
        'Huerta',
        'Preston',
        'Vance',
        'Barry',
        'Johns',
        'Eaton',
        'Blackwell',
        'Dyer',
        'Prince',
        'Macdonald',
        'Solomon',
        'Guevara',
        'Stafford',
        'English',
        'Hurst',
        'Woodard',
        'Cortes',
        'Shannon',
        'Kemp',
        'Nolan',
        'Mccullough',
        'Merritt',
        'Murillo',
        'Moon',
        'Salgado',
        'Strong',
        'Kline',
        'Cordova',
        'Barajas',
        'Roach',
        'Rosas',
        'Winters',
        'Jacobson',
        'Lester',
        'Knox',
        'Bullock',
        'Kerr',
        'Leach',
        'Meadows',
        'Orr',
        'Davila',
        'Whitehead',
        'Pruitt',
        'Kent',
        'Conway',
        'Mckee',
        'Barr',
        'David',
        'Dejesus',
        'Marin',
        'Berger',
        'Mcintyre',
        'Blankenship',
        'Gaines',
        'Palacios',
        'Cuevas',
        'Bartlett',
        'Durham',
        'Dorsey',
        'Mccall',
        'Odonnell',
        'Stein',
        'Browning',
        'Stout',
        'Lowery',
        'Sloan',
        'Mclean',
        'Hendricks',
        'Calhoun',
        'Sexton',
        'Chung',
        'Gentry',
        'Hull',
        'Duarte',
        'Ellison',
        'Nielsen',
        'Gillespie',
        'Buck',
        'Middleton',
        'Sellers',
        'Leblanc',
        'Esparza',
        'Hardin',
        'Bradshaw',
        'Mcintosh',
        'Howe',
        'Livingston',
        'Frost',
        'Glass',
        'Morse',
        'Knapp',
        'Herman',
        'Stark',
        'Bravo',
        'Noble',
        'Spears',
        'Weeks',
        'Corona',
        'Frederick',
        'Buckley',
        'Mcfarland',
        'Hebert',
        'Enriquez',
        'Hickman',
        'Quintero',
        'Randolph',
        'Schaefer',
        'Walls',
        'Trejo',
        'House',
        'Reilly',
        'Pennington',
        'Michael',
        'Conrad',
        'Giles',
        'Benjamin',
        'Crosby',
        'Fitzpatrick',
        'Donovan',
        'Mays',
        'Mahoney',
        'Valentine',
        'Raymond',
        'Medrano',
        'Hahn',
        'Mcmillan',
        'Small',
        'Bentley',
        'Felix',
        'Peck',
        'Lucero',
        'Boyle',
        'Hanna',
        'Pace',
        'Rush',
        'Hurley',
        'Harding',
        'Mcconnell',
        'Bernal',
        'Nava',
        'Ayers',
        'Everett',
        'Ventura',
        'Avery',
        'Pugh',
        'Mayer',
        'Bender',
        'Shepard',
        'Mcmahon',
        'Landry',
        'Case',
        'Sampson',
        'Moses',
        'Magana',
        'Blackburn',
        'Dunlap',
        'Gould',
        'Duffy',
        'Vaughan',
        'Herring',
        'Mckay',
        'Espinosa',
        'Rivers',
        'Farley',
        'Bernard',
        'Ashley',
        'Friedman',
        'Potts',
        'Truong',
        'Costa',
        'Correa',
        'Blevins',
        'Nixon',
        'Clements',
        'Fry',
        'Delarosa',
        'Best',
        'Benton',
        'Lugo',
        'Portillo',
        'Dougherty',
        'Crane',
        'Haley',
        'Phan',
        'Villalobos',
        'Blanchard',
        'Horne',
        'Finley',
        'Quintana',
        'Lynn',
        'Esquivel',
        'Bean',
        'Dodson',
        'Mullen',
        'Xiong',
        'Hayden',
        'Cano',
        'Levy',
        'Huber',
        'Richmond',
        'Moyer',
        'Lim',
        'Frye',
        'Sheppard',
        'Mccarty',
        'Avalos',
        'Booker',
        'Waller',
        'Parra',
        'Woodward',
        'Jaramillo',
        'Krueger',
        'Rasmussen',
        'Brandt',
        'Peralta',
        'Donaldson',
        'Stuart',
        'Faulkner',
        'Maynard',
        'Galindo',
        'Coffey',
        'Estes',
        'Sanford',
        'Burch',
        'Maddox',
        'Vo',
        'Oconnell',
        'Vu',
        'Andersen',
        'Spence',
        'Mcpherson',
        'Church',
        'Schmitt',
        'Stanton',
        'Leal',
        'Cherry',
        'Compton',
        'Dudley',
        'Sierra',
        'Pollard',
        'Alfaro',
        'Hester',
        'Proctor',
        'Lu',
        'Hinton',
        'Novak',
        'Good',
        'Madden',
        'Mccann',
        'Terrell',
        'Jarvis',
        'Dickson',
        'Reyna',
        'Cantrell',
        'Mayo',
        'Branch',
        'Hendrix',
        'Rollins',
        'Rowland',
        'Whitney',
        'Duke',
        'Odom',
        'Daugherty',
        'Travis',
        'Tang'
    ])[0]

    age = random.randint(18,65)

    frequent_flyer_status = random.choices([
        0,  #None
        1,  #Blue
        2,  #Bronze
        3,  #Silver
        4,  #Gold,
        5,  #VIP
    ],[
        100,
        50,
        20,
        10,
        5,
        1
    ])[0]

    new_passenger = Passenger(
        first_name = first_name,
        second_name = second_name,
        age = age,
        frequent_flyer_status = frequent_flyer_status
    )
    db.session.add(new_passenger)
    db.session.commit()


@passengers.route('/backend/create_new_passengers/<how_many>')
def create_new_passengers(how_many=1):

    for a in range(1, int(how_many)):
        create_new_passenger()

    return "Created " + str(how_many) + " new passengers"


@passengers.route('/inflight/passengers')
def list():

    return render_template('/passengers/passengers_list.html')


@passengers.route('/api/passengers/list/<unique_reference>')
def api_list(unique_reference):

    flight = Flight.query.filter_by(unique_reference=unique_reference).first()

    if flight is None:
        return jsonify ({
            'status': 'error',
            'error': 'flight not found'
        })

    seat_list = Seat.query.filter_by(flight = flight.id).all()

    seat_output_list = []
    occupied_seat_count = 0
    unoccupied_seat_count = 0

    for seat in seat_list:
        seat_dictionary = {
            'manifest_number': seat.manifest_number,
            'row': seat.row,
            'col': seat.col,
            'seat_type': seat.seat_type,
            'seat_type_text': seat.seat_type_text,
            'occupied': seat.occupied,
            'occupied_by_id': seat.occupied_by,
            'status': seat.status,
            'activity': seat.activity,
            'status_bladder_need': seat.status_bladder_need,
            'status_hunger': seat.status_hunger,
            'status_thirst': seat.status_thirst,
            'full_name': seat.full_name,
            'frequent_flyer_status': seat.frequent_flyer_status,
            'frequent_flyer_status_text': seat.frequent_flyer_status_text,
            'seat_number': None
        }
        seat_output_list.append(seat_dictionary)
        if seat.occupied == True: occupied_seat_count = occupied_seat_count + 1
        if seat.occupied == False: unoccupied_seat_count = unoccupied_seat_count + 1


    output_dictionary = {
        'status': 'success',
        'seat_count_unoccupied': unoccupied_seat_count,
        'seat_count_occupied': occupied_seat_count,
        'seat_count_total': occupied_seat_count + unoccupied_seat_count,
        'seats': seat_output_list
    }

    return jsonify(output_dictionary)







def fill_flight_with_passengers(flight_id):

    flight = Flight.query.filter_by(id=flight_id).first()

    if flight is None:
        return "error"

    # Delete any previous passengers
    Seat.query.filter_by(flight = flight_id).delete()


    how_many_passengers_exist = Passenger.query.count()
    list_of_already_loaded_passengers = []
    manifest_number = 1

    list_of_class_types = ['F', 'B', 'P', 'E']

    for class_code in list_of_class_types:
        if class_code == "F": number_to_load = flight.passengers_first_class
        if class_code == "B": number_to_load = flight.passengers_business_class
        if class_code == "P": number_to_load = flight.passengers_premium_class
        if class_code == "E": number_to_load = flight.passengers_economy_class

        # Populate each class
        for a in range(0, number_to_load):
            can_this_passenger_be_loaded = False

            while can_this_passenger_be_loaded == False:
                selected_passenger_id = random.randint(1, how_many_passengers_exist)

                if selected_passenger_id not in list_of_already_loaded_passengers:
                    can_this_passenger_be_loaded = True
                    list_of_already_loaded_passengers.append(selected_passenger_id)
                    new_seat = Seat(
                        flight = flight_id,
                        manifest_number = manifest_number,
                        seat_type=class_code,
                        occupied=True,
                        occupied_by=selected_passenger_id,
                        status="Waiting to Board",
                        status_bladder_need=random.randint(20,80),
                        status_hunger=random.randint(20,80),
                        status_thirst=random.randint(20,80)
                    )
                    db.session.add(new_seat)
                    db.session.commit()
                    manifest_number = manifest_number + 1

    return "ok"

# DEBUG ONLY
#@passengers.route('/passengers/populate')
#def test_passengers_populate():
#
#    return fill_flight_with_passengers(current_user.active_flight_id)

